# docker-compose.yml

version: '3.8'

services:
  frontend:
    build:
      context: ./ReactFrontend
    ports:
      - "5173:5173"
    volumes:
      - ./ReactFrontend:/app
    depends_on:
      - backend

  backend:
    build:
      context: ./FlaskBackend
    ports:
      - "5000:5000"
    volumes:
      - ./FlaskBackend:/app
